table BaseVendas
	lineageTag: 66a358f6-7ffd-42db-a048-461cae008cc3

	column 'Data da Venda'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2a7c05ac-692b-45d3-89f9-5b86ab4ce905
		summarizeBy: none
		sourceColumn: Data da Venda

		variation Variation
			isDefault
			relationship: a0e2ef43-51f8-4959-918f-be21f66cdda9
			defaultHierarchy: LocalDateTable_c1e56224-3e01-4650-a970-7920c927abbb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Produto
		dataType: string
		lineageTag: b973fdbe-fbe5-4712-9f3c-900448b22943
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 34699217-648a-41f9-88d0-e785fec01a31
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column PrecoUnitario
		dataType: double
		lineageTag: 81f748fd-dbcc-4a4f-ad37-c0ffd4df0085
		summarizeBy: sum
		sourceColumn: PrecoUnitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Custo Unitário'
		dataType: double
		lineageTag: 295b407a-8dd9-4ee7-9ab5-50419c37a07e
		summarizeBy: sum
		sourceColumn: Custo Unitário

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Marca
		dataType: string
		lineageTag: 8b0e48ab-f282-484d-9865-04bf9f21c837
		summarizeBy: none
		sourceColumn: Marca

		annotation SummarizationSetBy = Automatic

	column 'Qtd. Vendida'
		dataType: int64
		formatString: 0
		lineageTag: 7f1c6cbc-0df5-4425-8949-b3fc958f5996
		summarizeBy: sum
		sourceColumn: Qtd. Vendida

		annotation SummarizationSetBy = Automatic

	column País
		dataType: string
		lineageTag: b7c79752-6e31-44b0-a547-33c579aaccda
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column Continente
		dataType: string
		lineageTag: 5b32a11d-4554-44ee-adb0-f52817ff6463
		dataCategory: Continent
		summarizeBy: none
		sourceColumn: Continente

		annotation SummarizationSetBy = Automatic

	column Faturamento
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5fe394de-fa35-45bb-8905-ec0143a83374
		summarizeBy: sum
		sourceColumn: Faturamento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Cliente
		dataType: string
		lineageTag: 90510f3b-2530-4d6c-8054-9549e111a048
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	partition BaseVendas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("E:\UP_GRADE_VOLUME\PBI_Projetos_Explo\Dash_Vendas\Cópia de Vendas.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data da Venda", type date}, {"Produto", type text}, {"Categoria", type text}, {"PrecoUnitario", type number}, {"Custo Unitário", type number}, {"Marca", type text}, {"Qtd. Vendida", Int64.Type}, {"Nome Cliente", type text}, {"Localidade", type text}, {"Column10", type any}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Column10"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Linhas em Branco Removidas", "Localidade", Splitter.SplitTextByDelimiter(" - ", QuoteStyle.Csv), {"Localidade.1", "Localidade.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Localidade.1", type text}, {"Localidade.2", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Localidade.1", "País"}, {"Localidade.2", "Continente"}}),
				    #"Multiplicação Inserida" = Table.AddColumn(#"Colunas Renomeadas", "Multiplicação", each [PrecoUnitario] * [Qtd. Vendida], type number),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Multiplicação Inserida",{{"Multiplicação", "Faturamento"}}),
				    #"Coluna Personalizada Adicionada" = Table.AddColumn(#"Colunas Renomeadas1", "Personalizar", each Text.Combine({Text.Middle([Nome Cliente], 4), " ", Text.Start([Nome Cliente], 2)}), type text),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Coluna Personalizada Adicionada",{{"Personalizar", "Cliente"}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Renomeadas2",{"Nome Cliente"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Removidas1","Oceania","Austrália",Replacer.ReplaceText,{"Continente"})
				in
				    #"Valor Substituído"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

